姓名: name: get_bootimg_from_payload.bin:从Payload.bin获取启动图像

在:
看:
类型: [类型:[已开始]]
    
env:
  ROM_URL: ROM_URL:https://pan.baidu.com/s/1JtK0Uz_AFZwT-rGvnHo-LQ?pwd=772c
  TZ: TZ:亚洲/上海

工作:
制作:
运行中: 运行在:Ubuntu-最新

步骤:

    - 姓名: -名称:安装Python3.7
用途: 用途:actions/setup-python@v1
和:
Python版本: 3.7
    - 姓名: -名称:初始化环境
运行: |
cd ~
pip install bsdiff4
python -m pip install protobuf

    - 姓名: -名称:清理磁盘空间
运行: |
docker rmi `docker images -q'
sudo rm -rf /usr/share/dotnet/etc/mysql/etc/php/etc/apt/sources.list.d
sudo -E apt-get -y purge Azure-cli ghc* zulu* hhvm llvm* firefox Google* dotnet* powershell openjdk* mysql* php*
sudo -E apt-get -y autoremove --清除
sudo -E apt-get clean
        
    - 姓名: -名称:克隆工具源代码
运行: |
       cd ~
       git clone https://github.com/vm03/payload_dumper.git
       
  
    - name: Download the ROM
      run: |
       cd ~
       wget -O rom.zip $ROM_URL
   
    - name: unzip the ROM
      run: |
       cd ~
       unzip rom.zip -d payload_dumper
    
    - name: extract the payload.bin
      run: |
       cd ~
       cd payload_dumper
       python payload_dumper.py payload.bin
   

    
    - name: Upload the bootimg to WeTransfer
      run: |
        cd ~
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ~/payload_dumper/output/boot.img
